name: ExtraCash
version: '${project.version}'
main: br.com.extraplays.extracash.ExtraCash
authors: [ ExtraPlays ]
description: Adicione uma segunda economia para o seu servidor
website: extraplays.xyz
commands:
  cash:
    description: Mostra o cash